ORG 0000H
MOV P3,#00H  ; Initialize Port 3 to 0
RED1:
START: JB P3.0,RED   ; If P3.0 is set, jump to RED
LJMP YELLOW          ; Otherwise, jump to YELLOW

RED: ACALL INITLCD   ; Initialize the LCD
; Display "12345 ADITYA EXP" on the first line
MOV A,#'1'
ACALL DATAWRT 
MOV A,#'2'
ACALL DATAWRT
MOV A,#'3'
ACALL DATAWRT
MOV A,#'4'
ACALL DATAWRT
MOV A,#'5'
ACALL DATAWRT
MOV A,#' '
ACALL DATAWRT
MOV A,#'A'
ACALL DATAWRT
MOV A,#'D'
ACALL DATAWRT
MOV A,#'I'
ACALL DATAWRT
MOV A,#'T'
ACALL DATAWRT
MOV A,#'Y'
ACALL DATAWRT
MOV A,#'A'
ACALL DATAWRT
MOV A,#' '
ACALL DATAWRT
MOV A,#'E'
ACALL DATAWRT
MOV A,#'X'
ACALL DATAWRT
MOV A,#'P'
ACALL DATAWRT
; Move to second line and display "ARRIVING ON PF5"
MOV A,#0C0H 
ACALL CMDWRT 
MOV A,#'A'
ACALL DATAWRT
MOV A,#'R'
ACALL DATAWRT
MOV A,#'R'
ACALL DATAWRT
MOV A,#'I'
ACALL DATAWRT
MOV A,#'V'
ACALL DATAWRT
MOV A,#'I'
ACALL DATAWRT
MOV A,#'N'
ACALL DATAWRT
MOV A,#'G'
ACALL DATAWRT
MOV A,#' '
ACALL DATAWRT
MOV A,#'O'
ACALL DATAWRT
MOV A,#'N'
ACALL DATAWRT
MOV A,#' '
ACALL DATAWRT
MOV A,#'P'
ACALL DATAWRT
MOV A,#'F'
ACALL DATAWRT
MOV A,#'5'
ACALL DATAWRT
ACALL DELAY     ; Call delay
CLR P3.0         ; Clear P3.0
YELLOW: JB P3.1,YELLOW1  ; If P3.1 is set, jump to YELLOW1
LJMP RED1                 ; Otherwise, jump to RED1

YELLOW1: ACALL INITLCD   ; Initialize the LCD
; Display "12345 ADITYA EX P" on the first line
MOV A,#'1'
ACALL DATAWRT 
MOV A,#'2'
ACALL DATAWRT
MOV A,#'3'
ACALL DATAWRT
MOV A,#'4'
ACALL DATAWRT
MOV A,#'5'
ACALL DATAWRT
MOV A,#' '
ACALL DATAWRT
MOV A,#'A'
ACALL DATAWRT
MOV A,#'D'
ACALL DATAWRT
MOV A,#'I'
ACALL DATAWRT
MOV A,#'T'
ACALL DATAWRT
MOV A,#'Y'
ACALL DATAWRT
MOV A,#'A'
ACALL DATAWRT
MOV A,#' '
ACALL DATAWRT
MOV A,#'E'
ACALL DATAWRT
MOV A,#'X'
ACALL DATAWRT
MOV A,#'P'
ACALL DATAWRT
; Move to second line and display " IS ON PF5"
MOV A,#0C0H 
ACALL CMDWRT 
MOV A,#' '
ACALL DATAWRT
MOV A,#'I'
ACALL DATAWRT
MOV A,#'S'
ACALL DATAWRT
MOV A,#' '
ACALL DATAWRT
MOV A,#'O'
ACALL DATAWRT
MOV A,#'N'
ACALL DATAWRT
MOV A,#' '
ACALL DATAWRT
MOV A,#'P'
ACALL DATAWRT
MOV A,#'F'
ACALL DATAWRT
MOV A,#'5'
ACALL DATAWRT
ACALL DELAY     ; Call delay
CLR P3.1         ; Clear P3.1
GREEN: JB P3.2,GREEN1  ; If P3.2 is set, jump to GREEN1
LJMP YELLOW              ; Otherwise, jump to YELLOW

GREEN1: ACALL INITLCD   ; Initialize the LCD
; Display "12345 ADITYA EX P" on the first line
MOV A,#'1'
ACALL DATAWRT 
MOV A,#'2'
ACALL DATAWRT
MOV A,#'3'
ACALL DATAWRT
MOV A,#'4'
ACALL DATAWRT
MOV A,#'5'
ACALL DATAWRT
MOV A,#' '
ACALL DATAWRT
MOV A,#'A'
ACALL DATAWRT
MOV A,#'D'
ACALL DATAWRT
MOV A,#'I'
ACALL DATAWRT
MOV A,#'T'
ACALL DATAWRT
MOV A,#'Y'
ACALL DATAWRT
MOV A,#'A'
ACALL DATAWRT
MOV A,#' '
ACALL DATAWRT
MOV A,#'E'
ACALL DATAWRT
MOV A,#'X'
ACALL DATAWRT
MOV A,#'P'
ACALL DATAWRT
; Move to second line and display "READY TO LEAVE PF5"
MOV A,#0C0H 
ACALL CMDWRT 
MOV A,#'R'
ACALL DATAWRT
MOV A,#'D'
ACALL DATAWRT
MOV A,#'Y'
ACALL DATAWRT
MOV A,#' '
ACALL DATAWRT
MOV A,#'T'
ACALL DATAWRT
MOV A,#'O'
ACALL DATAWRT
MOV A,#' '
ACALL DATAWRT
MOV A,#'L'
ACALL DATAWRT
MOV A,#'E'
ACALL DATAWRT
MOV A,#'A'
ACALL DATAWRT
MOV A,#'V'
ACALL DATAWRT
MOV A,#'E'
ACALL DATAWRT
MOV A,#' '
ACALL DATAWRT
MOV A,#'P'
ACALL DATAWRT
MOV A,#'F'
ACALL DATAWRT
MOV A,#'5'
ACALL DATAWRT
ACALL DELAY     ; Call delay
CLR P3.2         ; Clear P3.2
LJMP RED1

; Subroutine to write data to the LCD
DATAWRT: MOV P1,A 
SETB P2.0 
CLR P2.1 
SETB P2.2 
ACALL DELAY1
CLR P2.2
ACALL DELAY2
RET

; Subroutine to write a command to the LCD
CMDWRT: MOV P1,A 
CLR P2.0 
CLR P2.1 
SETB P2.2 
ACALL DELAY1
CLR P2.2
ACALL DELAY2
RET

; Subroutine to initialize the LCD
INITLCD: MOV A,#38H 
ACALL CMDWRT 
MOV A,#0EH 
ACALL CMDWRT
MOV A,#01H 
ACALL CMDWRT
MOV A,#06H 
ACALL CMDWRT
MOV A,#80H 
ACALL CMDWRT
RET

; Delay subroutine
DELAY: MOV R0,#14H
UP2: MOV R1,#250D
UP1: MOV R2,#250D
MOV R3,#250D 
LABEL1: DJNZ R2,LABEL1
LABEL2: DJNZ R3,LABEL2
DJNZ R1,UP1
DJNZ R0,UP2
RET

; Shorter delay subroutine
DELAY2: MOV R3,#250D 
LOOP1: MOV R4,#255D
LOOP2: DJNZ R4,LOOP2
DJNZ R3,LOOP1
RET

; Another shorter delay subroutine
DELAY1: MOV R3,#10H 
LOOP3: MOV R4,#255
LOOP4: DJNZ R4,LOOP4
DJNZ R3,LOOP3
RET

END